# Generated by Django 5.2.1 on 2025-05-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_slug_to_userprofile'),
        ('api', '0003_dislike'),
    ]

    operations = [
    ]
