# Generated by Django 5.2.1 on 2025-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_update_userprofile_slug'),
        ('api', '0005_alter_userprofile_bio_and_more'),
    ]

    operations = [
    ]
